services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app
      - ./src/report:/app/report
    environment:
      - PYTHONUNBUFFERED=1
      - FORECAST_FILE_NAME=results_fi_fu
      - PYTHONPATH=/app # Ensure the src directory is in PYTHONPATH
    working_dir: /app # Set the working directory to /app (where src is mounted)
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
